#!/bin/bash
CFLAGS=`pkg-config gtk+-2.0 --cflags`
LIBS=`pkg-config gtk+-2.0 --libs`
gcc -W -Wall -O3 -lpthread  pxspec_mid.c px14.c fftwffft.c disp6.c plot6.c -lm -lfftw3f -lsig_px14400 $CFLAGS $LIBS
sudo rm pxspec_mid
mv a.out pxspec_mid
sudo chown root pxspec_mid
sudo chmod u+s pxspec_mid


