#!/bin/bash
CFLAGS=`pkg-config gtk+-2.0 --cflags`
LIBS=`pkg-config gtk+-2.0 --libs`
gcc -W -Wall -O3 -lpthread  pxspec_low2.c px14.c fftwffft.c disp6.c plot6.c -lm -lfftw3f -lsig_px14400 $CFLAGS $LIBS
sudo rm pxspec_low2
mv a.out pxspec_low2
sudo chown root pxspec_low2
sudo chmod u+s pxspec_low2


