#!/bin/bash
CFLAGS=`pkg-config --cflags gtk+-2.0`
LIBS=`pkg-config --libs gtk+-2.0`

#echo $CFLAGS
#echo $LIBS

# NOTE: The order of the flags matters!  llabjackusb needs to be near the end (after lm?) and the CFLAGS and LIBS need to be last (for GTK if used)

sudo rm pxspec

# PXSPEC - The main edges program
gcc -W -Wall -O3 -o pxspec -lpthread pxspec.c u3.c px14.c fftwffft.c labjack_edges.c fileio.c datetime.c parallelport.c -lm -llabjackusb -lfftw3f -lsig_px14400 $CFLAGS $LIBS

# WEATHER - A simple program to read from the weather station and display to stdout
gcc -W -Wall -O3 -o weather -lpthread labjack_edges.c u3.c datetime.c weather.c -lm -llabjackusb -lfftw3f -lsig_px14400 $CFLAGS $LIBS

# THERMCTL - A simple program to talk to the thermal controller, logging its set and actual temperature to /disk1/data/thermal.txt.
gcc -W -Wall -O3 -o thermctl thermctl.c -lm

# POWER_SWITCH - A simple program to talk to the networked power switch (over serial) to turn on/off the two outlets.
gcc -W -Wall -O3 -o power_switch power_switch.c


# Copy root user bit on pxspec so it runs as root regardless of who calls it
sudo chown root pxspec
sudo chmod u+s pxspec


